the:
  Far: 0.95
  Halves: 512
  Max: 512
  Reuse: true
  cliffs: 0.147
  dump: false
  eg: ALL
  far: 0.95
  file: ../../etc/data/auto93.csv
  go: false
  help: false
  min: 0.5
  p: 2
  quit: true
  rest: 4
  sample: 512
  seed: 937162211
