the:
  Far: 0.95
  Halves: 512.0
  Max: 512
  Reuse: true
  bins: 16.0
  cliffs: 0.147
  dump: false
  eg: ALL
  far: 0.95
  file: ../../etc/data/auto93.csv
  go: true
  help: false
  min: 0.5
  p: 2
  quit: false
  rest: 4
  sample: 512
  seed: 937162211.0
  bootstrap: 512
  conf: 0.05
  cohen: 0.35
#  Fmt: %6.2f
  width: 40
