name: Run Tests On Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install numpy
      #NOTE: we need to add to this whenever we add a test suite
      - name: Run HW1 Tests 
        run: |
          cd src/HW1
          python Tests.py
      - name: Run HW2 Tests 
        run: |
          cd src/HW2
          python Tests.py
      - name: Run HW3 Tests 
        run: |
          cd src/HW3
          python Tests.py
      - name: Run HW4 Tests 
        run: |
          cd src/HW4
          python Tests.py
      - name: Run HW5 Tests 
        run: |
          cd src/HW5
          python Tests.py
      - name: Run HW6 Tests 
        run: |
          cd src/HW6
          python Tests.py